// Sparse Atlas seed: broad roots with a few example children for interaction testing.
const forestData = [
  { id:"root-health", name:"Health & Wellbeing", votes:9800, rating:4.7, kind:"issue", color:"#71879a", children:[
    { id:"health-mental-access", name:"Mental Health Care Access", votes:4100, rating:4.8, kind:"issue" },
    { id:"health-community-clinics", name:"Community Health Clinics", votes:2800, rating:4.7, kind:"solution" }
  ]},
  { id:"root-economy", name:"Money, Work & Economy", votes:9400, rating:4.6, kind:"issue", color:"#71879a" },
  { id:"root-housing", name:"Housing & Built Environment", votes:9000, rating:4.7, kind:"issue", color:"#71879a", children:[
    { id:"housing-affordability", name:"Housing Affordability", votes:4700, rating:4.8, kind:"issue" },
    { id:"housing-mixed-income", name:"Mixed-Income Housing Development", votes:2400, rating:4.5, kind:"solution" }
  ]},
  { id:"root-education", name:"Education & Knowledge", votes:8500, rating:4.6, kind:"issue", color:"#71879a", children:[
    { id:"education-teacher-shortages", name:"Teacher Shortages", votes:3600, rating:4.6, kind:"issue" },
    { id:"education-adult-skills", name:"Free Adult Skills Programs", votes:2100, rating:4.5, kind:"solution" }
  ]},
  { id:"root-environment", name:"Environment & Natural World", votes:9300, rating:4.8, kind:"issue", color:"#71879a", children:[
    { id:"environment-biodiversity", name:"Biodiversity Loss", votes:3900, rating:4.7, kind:"issue" },
    { id:"environment-restoration", name:"Local Habitat Restoration", votes:2300, rating:4.6, kind:"solution" }
  ]},
  { id:"root-infrastructure", name:"Infrastructure, Transportation & Utilities", votes:8200, rating:4.5, kind:"issue", color:"#71879a" },
  { id:"root-energy", name:"Energy & Resources", votes:7600, rating:4.5, kind:"issue", color:"#71879a" },
  { id:"root-government", name:"Government & Public Institutions", votes:8300, rating:4.5, kind:"issue", color:"#71879a", children:[
    { id:"government-service-access", name:"Hard-to-Access Public Services", votes:3100, rating:4.5, kind:"issue" },
    { id:"government-one-stop", name:"One-Stop Public Service Portal", votes:1900, rating:4.4, kind:"solution" }
  ]},
  { id:"root-justice", name:"Law, Rights & Justice", votes:8500, rating:4.7, kind:"issue", color:"#71879a" },
  { id:"root-safety", name:"Safety, Conflict & Security", votes:7900, rating:4.6, kind:"issue", color:"#71879a" },
  { id:"root-technology", name:"Technology & Information", votes:8800, rating:4.7, kind:"issue", color:"#71879a", children:[
    { id:"technology-misinformation", name:"Online Misinformation", votes:4300, rating:4.7, kind:"issue" },
    { id:"technology-privacy", name:"Privacy-Preserving Digital Services", votes:2500, rating:4.6, kind:"solution" }
  ]},
  { id:"root-community", name:"Family, Relationships & Community", votes:7800, rating:4.6, kind:"issue", color:"#71879a" },
  { id:"root-culture", name:"Culture, Media & Recreation", votes:7200, rating:4.4, kind:"issue", color:"#71879a" },
  { id:"root-food", name:"Food & Agriculture", votes:7300, rating:4.6, kind:"issue", color:"#71879a" },
  { id:"root-migration", name:"Human Movement & Migration", votes:6900, rating:4.5, kind:"issue", color:"#71879a" },
  { id:"root-consumer", name:"Products, Services & Consumer Life", votes:8100, rating:4.6, kind:"issue", color:"#71879a" }
];

const host=document.querySelector("#viz"),breadcrumbHost=document.querySelector("#breadcrumbs"),resetButton=document.querySelector("#reset"),statusHost=document.querySelector("#status");
let width=host.clientWidth,height=host.clientHeight,focusPath=[],cameraY=0,worldHeight=height,levelCenters=[],touchStartY=null,touchLastY=null,touchMoved=false;
const svg=d3.select(host).append("svg").attr("role","img").attr("aria-label","Weighted clustered hierarchy").attr("viewBox",[0,0,width,height]),stage=svg.append("g").attr("class","stage"),nodeById=new Map(),parentById=new Map(),rootById=new Map();
function annotate(node,parent=null,root=node){nodeById.set(node.id,node);parentById.set(node.id,parent);rootById.set(node.id,root);(node.children||[]).forEach(child=>annotate(child,node,root));} forestData.forEach(root=>annotate(root));
function directScore(node){const votes=Math.max(1,node.votes||1),rating=Math.max(.5,Math.min(5,node.rating||3));return votes*(.35+.65*rating/5);} function aggregateScore(node){return directScore(node)+(node.children||[]).reduce((sum,child)=>sum+aggregateScore(child),0);} function rootColor(node){return rootById.get(node.id)?.color||"#71879a";} function lighten(hex,amount=.2){const c=d3.color(hex);return c?d3.interpolateRgb(c,d3.rgb(255,255,255))(amount):hex;} function compact(value){if(value>=1000)return `${(value/1000).toFixed(value>=10000?0:1)}k`;return `${Math.round(value)}`;} function polygonPath(poly){return `M${poly.map(p=>p.join(",")).join("L")}Z`;} function outerPolygon(w,h){return [[0,0],[w,0],[w,h],[0,h]];}
function layoutCluster(items,w,h,seedKey){const proxies=items.map(item=>({id:item.id,item,weight:Math.max(1,aggregateScore(item))})),root=d3.hierarchy({children:proxies}).sum(d=>d.weight||0),polygon=outerPolygon(w,h),seed=Array.from(seedKey).reduce((a,c)=>((a*31+c.charCodeAt(0))>>>0),2166136261)/4294967296;d3.voronoiTreemap().clip(polygon).prng(d3.randomLcg(seed||.42))(root);return{root,polygon};}
function polygonSpanAtY(poly,y){const xs=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];if(a[1]===b[1])continue;const lo=Math.min(a[1],b[1]),hi=Math.max(a[1],b[1]);if(y<lo||y>=hi)continue;const t=(y-a[1])/(b[1]-a[1]);xs.push(a[0]+t*(b[0]-a[0]));}xs.sort((a,b)=>a-b);return xs.length>=2?[xs[0],xs[xs.length-1]]:null;}
const labelMeasureCanvas=document.createElement("canvas"),labelMeasureContext=labelMeasureCanvas.getContext("2d");
function measuredWidth(text,fontSize,fontWeight){labelMeasureContext.font=`${fontWeight} ${fontSize}px system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif`;return labelMeasureContext.measureText(text).width;}
function layoutPolygonLabel(item,poly,cx,cy,baseFont,fontWeight){const words=item.name.split(/\s+/),maxLines=6,baseIconSize=Math.max(9,Math.min(16,baseFont*.78)),baseIconReserve=baseIconSize*1.45+Math.max(3,baseFont*.28);for(let scale=1;scale>=.2;scale-=.04){const effectiveFont=baseFont*scale,lineH=effectiveFont*1.08,pad=Math.max(2.5,effectiveFont*.42),iconReserve=baseIconReserve*scale,scoreH=effectiveFont*1.12;for(let lineCountGuess=1;lineCountGuess<=maxLines;lineCountGuess++){const blockH=(lineCountGuess-1)*lineH+scoreH+effectiveFont,y0=cy-blockH*.42,lines=[];let cursor=0,failed=false;for(let li=0;li<lineCountGuess&&cursor<words.length;li++){const y=y0+li*lineH,span=polygonSpanAtY(poly,y-effectiveFont*.25);if(!span){failed=true;break;}const available=Math.max(0,span[1]-span[0]-pad*2-(li===0?iconReserve:0));let line="";while(cursor<words.length){const candidate=line?`${line} ${words[cursor]}`:words[cursor],candidateWidth=measuredWidth(candidate,effectiveFont,fontWeight);if(candidateWidth<=available||!line){if(candidateWidth>available&&!line){failed=true;break;}line=candidate;cursor++;}else break;}if(failed||!line){failed=true;break;}lines.push({text:line,span,y,available,iconReserve:li===0?iconReserve:0});}if(failed||cursor<words.length||!lines.length)continue;const scoreY=y0+lines.length*lineH,scoreSpan=polygonSpanAtY(poly,scoreY),scoreText=compact(aggregateScore(item));if(!scoreSpan||measuredWidth(scoreText,effectiveFont*.92,fontWeight)>scoreSpan[1]-scoreSpan[0]-pad*2)continue;return{scale,baseFont,effectiveFont,lineH,lines,y0,iconReserve,scoreY,scoreSpan};}}return null;}
function renderCluster({items,x,y,w,h,selectedId=null,faded=false,interactive=true,className=""}){const {root,polygon}=layoutCluster(items,w,h,items.map(d=>d.id).join("-")),g=stage.append("g").attr("class",`cluster ${className}`).attr("transform",`translate(${x},${y})`);g.append("path").attr("class","cluster-outline").attr("d",polygonPath(polygon));const leaves=root.leaves(),cells=g.selectAll("g.cell").data(leaves,d=>d.data.id).join("g").attr("class",d=>`cell ${d.data.id===selectedId?"is-selected":""} ${faded&&d.data.id!==selectedId?"is-faded":""}`).attr("tabindex",interactive?0:null).attr("role",interactive?"button":null).attr("aria-label",d=>`${d.data.item.name}, ${compact(aggregateScore(d.data.item))} aggregate importance`).on("click",(event,d)=>{if(!interactive||touchMoved)return;event.stopPropagation();focusNode(d.data.item.id);}).on("keydown",(event,d)=>{if(interactive&&(event.key==="Enter"||event.key===" ")){event.preventDefault();focusNode(d.data.item.id);}});cells.append("path").attr("class","cell-shape").attr("d",d=>polygonPath(d.polygon)).attr("fill",d=>{const base=rootColor(d.data.item);return faded&&d.data.id!==selectedId?lighten(base,.7):lighten(base,.22);});cells.each(function(d){const item=d.data.item,[cx,cy]=d3.polygonCentroid(d.polygon),area=Math.abs(d3.polygonArea(d.polygon)),selected=item.id===selectedId,fontWeight=selected?750:620,baseFont=Math.max(9,Math.min(18,Math.sqrt(area)/8.5)),layout=layoutPolygonLabel(item,d.polygon,cx,cy,baseFont,fontWeight);if(!layout)return;const {scale,lines,y0,scoreSpan}=layout,localY=cy+(y0-cy)/scale,text=d3.select(this).append("text").attr("class","cell-label").attr("x",cx).attr("y",localY).attr("text-anchor","middle").attr("data-fit-scale",scale).attr("data-fit-anchor-x",cx).attr("data-fit-anchor-y",cy).attr("transform",`translate(${cx},${cy}) scale(${scale}) translate(${-cx},${-cy})`).style("font-size",`${baseFont}px`).style("font-weight",fontWeight);lines.forEach((line,i)=>{const lineCenter=(line.span[0]+line.span[1])/2,desiredX=i===0?lineCenter+line.iconReserve/2:lineCenter,localX=cx+(desiredX-cx)/scale;text.append("tspan").attr("x",localX).attr("dy",i===0?0:baseFont*1.08).text(line.text);});const scoreCenter=(scoreSpan[0]+scoreSpan[1])/2,scoreLocalX=cx+(scoreCenter-cx)/scale;text.append("tspan").attr("class","score-label").attr("x",scoreLocalX).attr("dy",baseFont*1.12).text(compact(aggregateScore(item)));});return{g,leaves};}
function currentNode(){return focusPath.length?nodeById.get(focusPath[focusPath.length-1]):null;} function siblingSet(node){if(!node)return forestData;const parent=parentById.get(node.id);return parent?parent.children||[]:forestData;} function pathForNode(id){const path=[];let node=nodeById.get(id);while(node){path.unshift(node.id);node=parentById.get(node.id);}return path;} function cameraBounds(){const toolbarAllowance=width<720?118:78,bottomAllowance=54;return{min:Math.min(0,height-worldHeight-bottomAllowance),max:Math.max(0,toolbarAllowance-20)};} function clampCamera(value){const{min,max}=cameraBounds();return Math.max(min,Math.min(max,value));} function applyCamera(animate=false){cameraY=clampCamera(cameraY);stage.interrupt();if(animate&&!window.matchMedia("(prefers-reduced-motion: reduce)").matches){stage.transition().duration(520).ease(d3.easeCubicOut).attr("transform",`translate(0,${cameraY})`);}else stage.attr("transform",`translate(0,${cameraY})`);} function scrollToDepth(index,animate=true){if(!levelCenters.length)return;const safeIndex=Math.max(0,Math.min(levelCenters.length-1,index)),viewportTarget=height*(width<720?.48:.5);cameraY=viewportTarget-levelCenters[safeIndex];applyCamera(animate);} function focusNode(id){const node=nodeById.get(id);if(!node)return;focusPath=pathForNode(id);render();scrollToDepth(focusPath.length-1,true);statusHost.textContent=(node.children||[]).length?`${node.name} selected. Showing ${node.children.length} example children.`:`${node.name} selected. No child nodes have been added yet.`;} function panToBreadcrumb(index){if(!focusPath.length)return;scrollToDepth(index,true);} function renderBreadcrumbs(){breadcrumbHost.replaceChildren();const all=document.createElement("button");all.type="button";all.textContent="All roots";all.addEventListener("click",()=>{focusPath=[];cameraY=0;render();});breadcrumbHost.append(all);focusPath.forEach((id,index)=>{const sep=document.createElement("span");sep.className="crumb-separator";sep.textContent="›";breadcrumbHost.append(sep);const button=document.createElement("button");button.type="button";button.textContent=nodeById.get(id).name;button.className=index===focusPath.length-1?"current":"";button.addEventListener("click",()=>panToBreadcrumb(index));breadcrumbHost.append(button);});} function selectedCentroid(rendered,id,x,y){const leaf=rendered.leaves.find(d=>d.data.id===id);if(!leaf)return null;const[cx,cy]=d3.polygonCentroid(leaf.polygon);return{x:x+cx,y:y+cy};} function levelGeometry(compactMobile,contentTop){const availableViewport=Math.max(360,height-contentTop-72),h=Math.max(compactMobile?340:420,Math.min(availableViewport*.92,compactMobile?width*.9:width*.38));return{x:0,w:width,h};}
function render(){width=host.clientWidth;height=host.clientHeight;svg.attr("viewBox",[0,0,width,height]);stage.selectAll("*").remove();levelCenters=[];renderBreadcrumbs();const compactMobile=width<720,contentTop=compactMobile?132:98,centerX=width/2,geometry=levelGeometry(compactMobile,contentTop),gap=compactMobile?88:110;if(!focusPath.length){cameraY=0;worldHeight=height;stage.attr("transform","translate(0,0)");renderCluster({items:forestData,x:0,y:contentTop,w:geometry.w,h:geometry.h,interactive:true,className:"root-overview"});stage.append("text").attr("class","canvas-caption").attr("x",centerX).attr("y",Math.min(height-22,contentTop+geometry.h+32)).attr("text-anchor","middle").text("Broad Atlas roots · sparse example children on selected topics");return;}let cursorY=contentTop;for(let depth=0;depth<focusPath.length;depth++){const selectedId=focusPath[depth],selected=nodeById.get(selectedId),siblings=depth===0?forestData:(parentById.get(selectedId)?.children||[selected]);renderCluster({items:siblings,x:0,y:cursorY,w:geometry.w,h:geometry.h,selectedId,faded:true,interactive:true,className:`context-cluster depth-${depth}`});levelCenters.push(cursorY+geometry.h/2);cursorY+=geometry.h+gap;}const selected=currentNode(),children=selected?.children||[];if(children.length){renderCluster({items:children,x:0,y:cursorY,w:geometry.w,h:geometry.h,interactive:true,className:"child-cluster"});levelCenters.push(cursorY+geometry.h/2);stage.append("text").attr("class","canvas-caption").attr("x",centerX).attr("y",cursorY-24).attr("text-anchor","middle").text(`${selected.name} · example children`);cursorY+=geometry.h+gap;}else{stage.append("text").attr("class","leaf-message").attr("x",centerX).attr("y",cursorY-30).attr("text-anchor","middle").text("No child nodes yet");}worldHeight=Math.max(height,cursorY+24);applyCamera(false);}
host.addEventListener("wheel",event=>{if(!focusPath.length||worldHeight<=height)return;event.preventDefault();cameraY-=event.deltaY*.78;applyCamera(false);},{passive:false});host.addEventListener("touchstart",event=>{if(!focusPath.length||event.touches.length!==1)return;touchStartY=event.touches[0].clientY;touchLastY=touchStartY;touchMoved=false;},{passive:true});host.addEventListener("touchmove",event=>{if(touchLastY==null||event.touches.length!==1||!focusPath.length)return;const y=event.touches[0].clientY,dy=y-touchLastY;if(Math.abs(y-touchStartY)>6)touchMoved=true;if(worldHeight>height){event.preventDefault();cameraY+=dy;applyCamera(false);}touchLastY=y;},{passive:false});host.addEventListener("touchend",()=>{touchStartY=null;touchLastY=null;setTimeout(()=>{touchMoved=false;},0);},{passive:true});resetButton.addEventListener("click",()=>{focusPath=[];cameraY=0;render();statusHost.textContent="Showing all broad Atlas roots.";});window.addEventListener("resize",()=>{render();applyCamera(false);});render();