(() => {
  const nodes = [
    {id:'atlas',type:'solution',title:'Building Atlas as a Public Think Tank',description:'Help us build a better way for people to think and solve problems together.\nUse this space to examine Atlas itself: what works, what does not, what is missing, and what could be done differently.',requestedChildTypes:[{type:'implementation',label:'Implementations'},{type:'challenge',label:'Challenges'},{type:'question',label:'Questions'}]},
    {id:'homelessness',type:'issue',title:'Solving the Homelessness Crisis',description:'Explore why people become or remain homeless, where current responses fall short, and what combinations of housing, services, prevention, treatment, public policy, community support, and other approaches could improve outcomes.',requestedChildTypes:[{type:'issue',label:'Sub-issues'},{type:'solution',label:'Solutions'},{type:'question',label:'Questions'}]},
    {id:'better-world',type:'question',title:'What ideas could help make the world better?',description:'An intentionally broad inquiry where anyone can contribute an idea they believe could make the world better.\nIdeas can be large or small, practical or ambitious, local or global.',requestedChildTypes:[{type:'solution',label:'Ideas'},{type:'question',label:'Questions'}]},

    {id:'encampments',type:'issue',title:'Large homeless encampments and unsheltered homelessness',description:'Explore the problems that arise when people live outdoors or in large encampments without stable access to sanitation, safety, storage, shelter, and essential services.',requestedChildTypes:[{type:'solution',label:'Solutions'},{type:'cause',label:'Causes'},{type:'question',label:'Questions'}]},
    {id:'addiction',type:'issue',title:'Substance use and addiction among people experiencing homelessness',description:'Examine how substance use and addiction can contribute to homelessness, how homelessness can make recovery more difficult, and where treatment and support systems fall short.',requestedChildTypes:[{type:'solution',label:'Solutions'},{type:'evidence',label:'Evidence'},{type:'question',label:'Questions'}]},
    {id:'mental-health',type:'issue',title:'Severe mental illness and lack of consistent treatment',description:'Explore the challenges faced by people experiencing homelessness who also live with severe mental illness, especially when consistent treatment and follow-up care are difficult to access.',requestedChildTypes:[{type:'solution',label:'Solutions'},{type:'evidence',label:'Evidence'}]},
    {id:'housing',type:'issue',title:'Lack of affordable and available housing',description:'Examine how housing costs, limited supply, low vacancy, income constraints, and other barriers can make stable housing inaccessible or difficult to regain.',requestedChildTypes:[{type:'solution',label:'Solutions'},{type:'evidence',label:'Evidence'},{type:'question',label:'Questions'}]},
    {id:'escape-street',type:'issue',title:'Difficulty escaping homelessness once someone is on the street',description:'Explore the interconnected practical barriers that can make it difficult to regain stability after becoming homeless.',requestedChildTypes:[{type:'solution',label:'Solutions'},{type:'barrier',label:'Barriers'}]},
    {id:'prevention',type:'issue',title:'People becoming homeless in the first place',description:'Explore the pathways that lead people into homelessness and how earlier intervention might prevent it.',requestedChildTypes:[{type:'solution',label:'Prevention ideas'},{type:'cause',label:'Causes'}]},
    {id:'fragmented-services',type:'issue',title:'Fragmented homelessness services',description:'Examine how assistance can be spread across different agencies, eligibility systems, locations, schedules, and processes that are difficult to navigate while homeless.',requestedChildTypes:[{type:'solution',label:'Solutions'},{type:'example',label:'Examples'}]},
    {id:'employment-center',type:'solution',title:'Create one-stop employment transition centers for people experiencing homelessness',description:'Create accessible places where people experiencing homelessness can get practical support to prepare for, find, and begin work.\nThe idea is to bring together useful resources, preparation, assistance, and connections rather than requiring someone to navigate every barrier separately.',requestedChildTypes:[{type:'challenge',label:'Challenges'},{type:'implementation',label:'Implementations'},{type:'question',label:'Questions'}]},

    {id:'surplus-food',type:'solution',title:'Make it easier to redirect surplus food',description:'Restaurants and other food businesses can use simple, repeatable processes to route safe surplus food toward people or organizations that can use it instead of discarding it.',requestedChildTypes:[{type:'challenge',label:'Challenges'},{type:'implementation',label:'Implementations'},{type:'support',label:'Yays'},{type:'objection',label:'Nays'}]},
    {id:'food-safety',type:'challenge',title:'Food safety and liability can complicate surplus food redistribution',description:'Surplus food has to remain safe through storage, pickup, transportation, and delivery.\nFood businesses may also hesitate to donate when they are uncertain about handling requirements or potential liability.',requestedChildTypes:[{type:'solution',label:'Ways to address this'},{type:'evidence',label:'Evidence'}]},
    {id:'food-logistics',type:'challenge',title:'Reliable logistics and timing',description:'Surplus food often becomes available unpredictably and may have a short usable window.\nCoordinating pickup, transportation, refrigeration, storage capacity, and delivery quickly enough can be difficult even when plenty of food exists.',requestedChildTypes:[{type:'solution',label:'Ways to address this'},{type:'implementation',label:'Implementations'}]},

    {id:'social-media',type:'solution',title:'Design social media to channel attention toward collective problem-solving',description:'Explore how social media could be intentionally designed to direct more human attention and participation toward constructive collaboration and solving shared problems.',requestedChildTypes:[{type:'challenge',label:'Challenges'},{type:'implementation',label:'Implementations'},{type:'question',label:'Questions'}]},
    {id:'ranked-choice',type:'solution',title:'Use Ranked-Choice Voting in More Elections',description:'Allow voters to rank candidates in order of preference instead of choosing only one.\nThe approach can reduce spoiler effects and give voters more freedom to support preferred candidates without relying as heavily on strategic voting.',requestedChildTypes:[{type:'challenge',label:'Challenges'},{type:'implementation',label:'Implementations'},{type:'support',label:'Yays'},{type:'objection',label:'Nays'}]},
    {id:'rcv-learning',type:'challenge',title:'Voters may need time to learn a new ballot system',description:'Switching from choose-one ballots to ranked ballots introduces a learning curve.\nClear ballot design, voter education, and transparent counting rules would be important parts of a successful transition.',requestedChildTypes:[{type:'solution',label:'Ways to address this'}]},
    {id:'rcv-pilot',type:'implementation',title:'Adopt ranked-choice voting in local elections first',description:'Cities or local jurisdictions could introduce ranked-choice voting for selected elections, publish clear guidance, and evaluate the results before broader adoption.',requestedChildTypes:[{type:'challenge',label:'Challenges'},{type:'evidence',label:'Results / evidence'}]},
    {id:'rcv-candidates',type:'support',title:'Ranked-choice voting could encourage more people to run for office',description:'Candidates outside the usual pathways might have more reason to enter races because voters could support them without the same spoiler concerns.',requestedChildTypes:[{type:'evidence',label:'Evidence'},{type:'objection',label:'Counterpoints'}]},
    {id:'rcv-complexity',type:'objection',title:'Ranked-choice voting can make elections harder to understand',description:'Critics may argue that multiple rankings and transfer rounds make the final result less immediately intuitive than a simple plurality count.',requestedChildTypes:[{type:'evidence',label:'Evidence'},{type:'response',label:'Responses'}]},
    {id:'tool-sharing',type:'solution',title:'Create neighborhood libraries for rarely used tools',description:'Neighbors could share tools and equipment that most people only need occasionally instead of every household buying its own.',requestedChildTypes:[{type:'challenge',label:'Challenges'},{type:'implementation',label:'Implementations'}]},
    {id:'class-participation',type:'solution',title:'Share simple teaching practices that improve participation',description:'When a teacher discovers a small change that substantially improves student participation, make the practice easy for others to understand, adapt, test, and improve.',requestedChildTypes:[{type:'example',label:'Examples'},{type:'challenge',label:'Challenges'}]},
    {id:'shorter-meetings',type:'solution',title:'Use simple processes to make meetings shorter',description:'Teams can adopt lightweight meeting practices that reduce unnecessary discussion, clarify decisions, and return time to participants.',requestedChildTypes:[{type:'example',label:'Examples'},{type:'challenge',label:'Challenges'}]},
    {id:'accessible-info',type:'solution',title:'Make public information easier to access across languages',description:'Public-facing information can be designed and translated so people who do not primarily speak the dominant local language can more easily understand services, instructions, opportunities, and decisions.',requestedChildTypes:[{type:'challenge',label:'Challenges'},{type:'implementation',label:'Implementations'}]}
  ];

  const hierarchy = [
    ['homelessness','encampments'],['homelessness','addiction'],['homelessness','mental-health'],['homelessness','housing'],['homelessness','escape-street'],['homelessness','prevention'],['homelessness','fragmented-services'],['homelessness','employment-center'],['homelessness','surplus-food'],
    ['surplus-food','food-safety'],['surplus-food','food-logistics'],
    ['better-world','ranked-choice'],['better-world','tool-sharing'],['better-world','class-participation'],['better-world','shorter-meetings'],['better-world','surplus-food'],['better-world','accessible-info'],['better-world','social-media'],
    ['ranked-choice','rcv-learning'],['ranked-choice','rcv-pilot'],['ranked-choice','rcv-candidates'],['ranked-choice','rcv-complexity'],
    ['atlas','social-media']
  ].map(([parentId,childId])=>({parentId,childId}));

  const relationships = [
    {from:'surplus-food',to:'homelessness',relationshipType:'helps-address',label:'Helps address'},
    {from:'social-media',to:'atlas',relationshipType:'implemented-by',label:'Implemented by'}
  ];

  const rootIds = ['atlas','homelessness','better-world'];
  window.ATLAS_DATA = {nodes,hierarchy,relationships,rootIds};
})();
